# -*- coding: utf-8 -*-
"""plantsdisease_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iCf3sjYyWeLsLzy1dVXNTwj_mtFnP4ep
"""

# ===============================
# Check Files in leaf Folder
# ===============================
import os

# Unzip the leaf.zip file if it exists and the 'rice_leaf_diseases' directory does not.
if not os.path.exists('rice_leaf_diseases') and os.path.exists('leaf.zip'):
    import zipfile
    with zipfile.ZipFile('leaf.zip', 'r') as zip_ref:
        zip_ref.extractall('.')
        print("Unzipped 'leaf.zip' successfully, creating 'rice_leaf_diseases' directory.")

# Now try listing the directory
if os.path.exists('rice_leaf_diseases'):
    print("Contents of 'rice_leaf_diseases' directory:")
    print(os.listdir("rice_leaf_diseases"))
else:
    print("Error: 'rice_leaf_diseases' directory still not found after attempting to unzip.")

# ===============================
# Import Libraries
# ===============================
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras import layers, models
import matplotlib.pyplot as plt
import numpy as np
from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns

# ===============================
# Data Preprocessing
# ===============================
IMG_SIZE = 224
BATCH_SIZE = 32

train_datagen = ImageDataGenerator(
    rescale=1./255,
    validation_split=0.2,
    rotation_range=20,
    width_shift_range=0.2,
    height_shift_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True
)

train_generator = train_datagen.flow_from_directory(
    "rice_leaf_diseases",   # Changed from 'leaf' to 'rice_leaf_diseases'
    target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    subset='training'
)

val_generator = train_datagen.flow_from_directory(
    "rice_leaf_diseases",   # Changed from 'leaf' to 'rice_leaf_diseases'
    target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    subset='validation'
)

# ===============================
# Build Model (Transfer Learning)
# ===============================
base_model = MobileNetV2(input_shape=(224, 224, 3),
                         include_top=False,
                         weights='imagenet')

base_model.trainable = False

model = models.Sequential([
    base_model,
    layers.GlobalAveragePooling2D(),
    layers.Dense(128, activation='relu'),
    layers.Dropout(0.3),
    layers.Dense(train_generator.num_classes, activation='softmax')
])

model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

model.summary()

# ===============================
# Train Model
# ===============================
history = model.fit(
    train_generator,
    validation_data=val_generator,
    epochs=10
)

# ===============================
# Evaluate Model
# ===============================
val_loss, val_accuracy = model.evaluate(val_generator)
print("\nValidation Accuracy:", val_accuracy)

# ===============================
# Classification Report
# ===============================
val_generator.reset()
predictions = model.predict(val_generator)
y_pred = np.argmax(predictions, axis=1)
y_true = val_generator.classes

print("\nClassification Report:\n")
print(classification_report(y_true, y_pred,
                            target_names=val_generator.class_indices.keys()))

# ===============================
# Confusion Matrix
# ===============================
cm = confusion_matrix(y_true, y_pred)

plt.figure(figsize=(10,8))
sns.heatmap(cm, annot=True, fmt="d",
            xticklabels=val_generator.class_indices.keys(),
            yticklabels=val_generator.class_indices.keys())
plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

# ===============================
# Accuracy Graph
# ===============================
plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.legend()
plt.title("Training vs Validation Accuracy")
plt.show()